### ISSUE TITLE
datascripts: quotation marks are not escaped in generated sql query

### ISSUE THREAD

**Issue by ghost** [tswow/tswow#287]
```typescript
const remy_two_times = std.CreatureTemplates.load(241)
    remy_two_times.Models.setId(0, 218)
    remy_two_times.spawn("classicplus", "npc_goldshire_remy", Pos(0,-9547.592773,179.567825,56.445507,5.841067));
```

The above snippet gives the following error when building datascripts. The NPCs name is `Remy "Two Times"` and the culprit seems to be quotations marks in his nickname not being escaped in the generated query.

```
> build datascripts
Building DataScripts for dataset default
(For SQL "INSERT INTO creature_template (entry,difficulty_entry_1,difficulty_entry_2,difficulty_entry_3,KillCredit1,KillCredit2,modelid1,modelid2,modelid3,modelid4,name,subname,IconName,gossip_menu_id,minlevel,maxlevel,exp,faction,npcflag,speed_walk,speed_run,scale,rank,dmgschool,BaseAttackTime,RangeAttackTime,BaseVariance,RangeVariance,unit_class,unit_flags,unit_flags2,dynamicflags,family,type,type_flags,lootid,pickpocketloot,skinloot,PetSpellDataId,VehicleId,mingold,maxgold,AIName,MovementType,HoverHeight,HealthModifier,ManaModifier,ArmorModifier,DamageModifier,ExperienceModifier,RacialLeader,movementId,RegenHealth,mechanic_immune_mask,spell_school_immune_mask,flags_extra,ScriptName,VerifiedBuild) VALUES (241,0,0,0,0,0,218,0,0,0,"Remy "Two Times"",null,null,0,5,5,0,12,2,1,1.14286,1,0,0,1500,2000,1,1,1,512,2048,0,0,7,0,0,0,0,0,0,0,0,"",0,1,1,1,1,1,1,0,0,1,0,0,66,"",12340) ON DUPLICATE KEY UPDATE entry = 241, difficulty_entry_1 = 0, difficulty_entry_2 = 0, difficulty_entry_3 = 0, KillCredit1 = 0, KillCredit2 = 0, modelid1 = 218, modelid2 = 0, modelid3 = 0, modelid4 = 0, name = "Remy "Two Times"", subname = null, IconName = null, gossip_menu_id = 0, minlevel = 5, maxlevel = 5, exp = 0, faction 
= 12, npcflag = 2, speed_walk = 1, speed_run = 1.14286, scale = 1, rank = 0, dmgschool = 0, BaseAttackTime = 1500, RangeAttackTime = 2000, BaseVariance = 1, RangeVariance = 1, unit_class = 1, unit_flags = 512, unit_flags2 = 2048, dynamicflags = 0, family = 0, type = 7, type_flags = 0, lootid = 0, pickpocketloot = 0, skinloot = 0, PetSpellDataId = 0, VehicleId = 0, mingold = 0, maxgold = 0, AIName = "", MovementType = 0, HoverHeight = 1, HealthModifier = 1, ManaModifier = 1, ArmorModifier = 1, DamageModifier = 1, ExperienceModifier = 1, RacialLeader = 0, movementId = 0, RegenHealth = 1, mechanic_immune_mask = 0, spell_school_immune_mask = 0, flags_extra = 66, ScriptName = "", VerifiedBuild = 12340")
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Two Times"",null,null,0,5,5,0,12,2,1,1.14286,1,0,0,1500,2000,1,1,1,512,2048,0...' at line 1Error: (For SQL "INSERT INTO creature_template (entry,difficulty_entry_1,difficulty_entry_2,difficulty_entry_3,KillCredit1,KillCredit2,modelid1,modelid2,modelid3,modelid4,name,subname,IconName,gossip_menu_id,minlevel,maxlevel,exp,faction,npcflag,speed_walk,speed_run,scale,rank,dmgschool,BaseAttackTime,RangeAttackTime,BaseVariance,RangeVariance,unit_class,unit_flags,unit_flags2,dynamicflags,family,type,type_flags,lootid,pickpocketloot,skinloot,PetSpellDataId,VehicleId,mingold,maxgold,AIName,MovementType,HoverHeight,HealthModifier,ManaModifier,ArmorModifier,DamageModifier,ExperienceModifier,RacialLeader,movementId,RegenHealth,mechanic_immune_mask,spell_school_immune_mask,flags_extra,ScriptName,VerifiedBuild) VALUES (241,0,0,0,0,0,218,0,0,0,"Remy "Two Times"",null,null,0,5,5,0,12,2,1,1.14286,1,0,0,1500,2000,1,1,1,512,2048,0,0,7,0,0,0,0,0,0,0,0,"",0,1,1,1,1,1,1,0,0,1,0,0,66,"",12340) ON DUPLICATE KEY UPDATE entry = 241, difficulty_entry_1 = 0, difficulty_entry_2 = 0, difficulty_entry_3 = 0, KillCredit1 = 0, KillCredit2 = 0, modelid1 = 218, modelid2 = 0, modelid3 = 0, modelid4 = 0, name = "Remy "Two Times"", subname = null, IconName = null, gossip_menu_id = 0, minlevel = 5, maxlevel = 5, exp = 0, faction = 12, npcflag = 2, speed_walk = 1, speed_run = 1.14286, scale = 1, rank = 0, dmgschool = 0, BaseAttackTime = 1500, RangeAttackTime = 2000, BaseVariance = 1, RangeVariance = 1, unit_class = 1, unit_flags = 512, unit_flags2 = 2048, dynamicflags = 0, family = 0, type = 7, type_flags = 0, lootid = 0, pickpocketloot = 0, skinloot = 0, PetSpellDataId = 0, VehicleId = 0, mingold = 0, maxgold = 0, AIName = "", MovementType = 0, HoverHeight = 1, HealthModifier = 1, ManaModifier = 1, ArmorModifier = 1, DamageModifier = 1, ExperienceModifier = 1, RacialLeader = 0, movementId = 
nd.js:28:26)
    at Connection.handlePacket (C:\projects\wow\server\tswow\node_modules\mysql2\lib\connection.js:425:32)
    at PacketParser.onPacket (C:\projects\wow\server\tswow\node_modules\mysql2\lib\connection.js:75:12)
    at PacketParser.executeStart (C:\projects\wow\server\tswow\node_modules\mysql2\lib\packet_parser.js:75:16)
    at Socket.<anonymous> (C:\projects\wow\server\tswow\node_modules\mysql2\lib\connection.js:82:25)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
Error: Failed to rebuild patches```

**Comment by ihm-tswow** [comment]
there's a temporary fix on the repo that you can copypaste as is (it's valid javascript) into your `bin/scripts/tswow/wotlkdata/sql/SQLRow.js`: https://github.com/tswow/tswow/commit/c36c051b12ef5651f6da7f16906129e1c4202349

It's not very rigorous because we're going to switch to prepared statements now that we're on mysql2

**Comment by ghost** [comment]
Thanks for the heads up. Tried searching for similar issues but didn't see #251.
Closing this.
