### ISSUE TITLE
TSWoW crashes if you create a file named "scripts" in a module

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#33]
Log:
```
*\tswow-scripts\util\FileSystem.ts:271
            throw new Error(`${dname} is not a directory!`);
                  ^
Error: modules\test\scripts is not a directory!
    at mkDirs (\*tswow-scripts\util\FileSystem.ts:271:19)
    at Object.write (\*tswow-scripts\util\FileSystem.ts:354:9)
    at \*tswow-scripts\runtime\Modules.ts:343:25
    at Array.forEach (<anonymous>)
    at refreshModules (\*tswow-scripts\runtime\Modules.ts:303:40)      
    at Timeout._onTimeout (\*tswow-scripts\runtime\Modules.ts:442:13)  
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

This might also happen to data/assets.

**Comment by tswow-admin** [comment]
Fix: 74d135e30f107ae6abf368429250f1d9a3ac9728
