### ISSUE TITLE
Transpiler errors give no useful output

### ISSUE THREAD

**Issue by tswow-admin** [tswow/tswow#73]
**Describe the bug**
Compiler errors give no useful output:

```
Error: Command failed: node bin\scripts\transpiler\wowts.js test
child_process.js:674
    throw err;


Error: Command failed: "bin/cmake/bin/cmake.exe" --build modules/test/scripts/build/lib --config Release
    at checkExecSyncError (child_process.js:635:11)
    at Object.execSync (child_process.js:671:15)
    at Object.<anonymous> (C:\dev\wow\tswow-install\bin\scripts\transpiler\wowts.js:75:15) 
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)    
    at internal/main/run_main_module.js:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 18620,
  stdout: null,
  stderr: null
}
```

**To Reproduce**
1. Create a new module with the following live script: ```abc``` (compiler error)
2. Re-compile using `build scripts`

**Expected behavior**
The error message should say something about what went wrong

**Comment by tswow-admin** [comment]
Fixed
